Add convert decode annotation regression test
ucb-bar/chiseltest pull request #698
Opened 2024-01-01 09:37 UTC by Discreater

Related to #697.

The `Booth` module and test is from https://github.com/sequencer/arithmetic/blob/master/arithmetic/src/multiplier/Booth.scala.

Feel free to modify anything.

2024-01-01 09:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ucb-bar/chiseltest?pullRequest=698) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ucb-bar/chiseltest?pullRequest=698) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ucb-bar/chiseltest?pullRequest=698) it.</sub>

2024-01-03 14:14 UTC, ekiwi requested changes
I like the regression test!

I do think the change can be simplified though by just ignoring the annotation instead of adding an unused annotation to `firrtl`. What do you think?

2024-01-03 14:14 UTC, ekiwi commented on src/main/scala/chiseltest/simulator/ChiselBridge.scala
> +      Some(firrtl2.annotations.DecodeTableAnnotation(convert(target), truthTable, minimizedTable))
Can you change this to something like:
```
... =>
  None // ignore DecodeTableAnnotation since it is not needed by the firrtl compiler
```

2024-01-03 15:45 UTC, Discreater commented
Thanks. I agree with you.

2024-01-03 16:35 UTC, ekiwi approved these changes
Awesome! Thanks and congratulations on your first PR to `chiseltest`!

2024-01-03 16:35 UTC, merged